version: "3.8"
name: findit
services:
  store:
    image: redis:alpine
    environment:
      - REDIS_PROTECTED_MODE=no
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 3
  
  database:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=webserver
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pg-data
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 5s
      timeout: 10s
      retries: 3

  backend:
    develop:
      watch:
        - path: ./applications/backend
          action: sync
          target: /dsahboard/apps/backend

  frontend:
    develop:
      watch:
        - path: ./applications/frontend
          action: sync
          target: /dsahboard/apps/frontend

  nginx:
    image: nginx:alpine