version: '3.9'
name: findit-test
services:
  database:
    extends:
      file: docker-compose.yml
      service: database

    build:
      args:
        - ENV=test

  backend:
    extends:
      file: docker-compose.yml
      service: backend

    build:
      target: test
      args:
        - ENV=test

    depends_on:
      database:
        condition: service_healthy

    restart: no

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

    build:
      target: test
      args:
        - ENV=test

    env_file:
      - ./applications/frontend/.env.development

    restart: no
