version: "3.9"
services:
  database:
    container_name: database
    build:
      context: applications/database/
      dockerfile: Dockerfile
      target: test

  backend:
    container_name: backend
    build:
      context: applications/backend/
      dockerfile: Dockerfile
      target: test

    depends_on:
      database:
        condition: service_healthy