version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: applications/backend/
      dockerfile: Dockerfile
      target: dev

    restart: always

    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: applications/frontend/
      dockerfile: Dockerfile
      target: dev

    ports:
      - "0.0.0.0:80:3000"

    restart: always

    depends_on:
      - backend

  database:
    container_name: database
    build:
      context: applications/database/
      dockerfile: Dockerfile
      target: dev

    restart: always

    volumes:
      - ./applications/database/data/dev:/var/lib/postgresql/data/pg-data
volumes:
    postgres:
