version: '3.9'
name: findit-development
services:
  store:
    extends:
      file: docker-compose.yml
      service: store
    build:
      args:
        - ENV=development
    volumes:
      - ./applications/store/data/development:/data:rw
    networks:
      - default

  database:
    extends:
      file: docker-compose.yml
      service: database
    environment:
      - POSTGRES_DB=development
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "webserver", "-d", "development" ]
      start_period: "3s"
    volumes:
      - ./applications/database/data/development:/var/lib/postgresql/data/pg-data:rw
    networks:
      - default

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      target: backend-development
      args:
        - ENV=development
    depends_on:
      database:
        condition: service_healthy
      store:
        condition: service_healthy
    env_file:
      - ./applications/backend/.env.development
    networks:
      default:
        aliases:
          - api.findit.test

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      target: frontend-development
      args:
        - ENV=development
    env_file:
      - ./applications/frontend/.env.development
    networks:
      - default

  nginx:
    extends:
      file: docker-compose.yml
      service: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    networks:
      - default

networks:
  default:
