version: "3.9"
name: findit
services:
  store:
    image: redis:latest
    environment:
      - REDIS_PROTECTED_MODE=no
    expose:
      - 6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      start_period: "3s"


  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=webserver
      - POSTGRES_PASSWORD=123456
      - PGDATA=/var/lib/postgresql/data/pg-data
    expose:
      - 5432

  backend:
    develop:
      watch:
        - path: ./applications/backend
          action: sync
          target: /project/apps/backend

  frontend:
    develop:
      watch:
        - path: ./applications/frontend
          action: sync
          target: /project/apps/frontend

  nginx:
    image: nginx:latest