version: '3.9'
name: findit-production
services:
  database:
    extends:
      file: docker-compose.yml
      service: database

    build:
      args:
        - ENV=production

    volumes:
      - ./applications/database/data/production:/var/lib/postgresql/data/pg-data:rw


  backend:
    extends:
      file: docker-compose.yml
      service: backend

    build:
      target: production
      args:
        - ENV=production

    depends_on:
      database:
        condition: service_healthy

    env_file:
      - ./applications/backend/.env.production

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

    build:
      target: production
      args:
        - ENV=production

    depends_on:
      backend:
        condition: service_healthy

    env_file:
        - ./applications/frontend/.env.development

    ports:
      - '0.0.0.0:80:3000'