version: "3.9"
services:
  backend:
    container_name: backend

    build:
      context: applications/backend/
      dockerfile: Dockerfile
      target: dev

    develop:
      watch:
        - path: ./applications/backend/
          action: sync
          target: /app
          ignore:
            - node_modules/

    depends_on:
      database:
        condition: service_healthy

  frontend:
    container_name: frontend

    develop:
      watch:
        - path: ./applications/frontend/
          action: sync
          target: /app

    build:
      context: applications/frontend/
      dockerfile: Dockerfile
      target: dev

    ports:
      - "0.0.0.0:80:3000"

    restart: always

    depends_on:
      backend:
        condition: service_healthy
        restart: true

  database:
    container_name: database
    build:
      context: applications/database/
      dockerfile: Dockerfile
      target: dev

    restart: always

    volumes:
      - ./applications/database/data/dev:/var/lib/postgresql/data/pg-data
