version: '3.9'
name: findit-development
services:
  store:
    extends:
      file: docker-compose.yml
      service: store

    build:
      args:
        - ENV=development

    volumes:
      - ./applications/store/data/development:/data:rw

  database:
    extends:
      file: docker-compose.yml
      service: database

    build:
      args:
        - ENV=development

    volumes:
      - ./applications/database/data/development:/var/lib/postgresql/data/pg-data:rw


  backend:
    extends:
      file: docker-compose.yml
      service: backend

    build:
      target: development
      args:
        - ENV=development

    depends_on:
      database:
        condition: service_healthy

    env_file:
      - ./applications/backend/.env.development

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend

    build:
      target: development
      args:
        - ENV=development

    depends_on:
      backend:
        condition: service_healthy

    env_file:
        - ./applications/frontend/.env.development

    ports:
      - '0.0.0.0:80:3000'