version: "3.9"
services:
  backend:
    build:
      context: applications/backend/

    ports:
      - "1105:4000"
      - "127.0.0.1:1105:4000"

    restart: always

    depends_on:
      - database

  frontend:
    build:
      context: applications/frontend/

    ports:
      - "80:3000"
      - "127.0.0.1:80:3000"

    restart: always

    depends_on:
      - backend

  database:
    image: postgres:latest
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: findit
      POSTGRES_USER: webserver
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata

    restart: always

    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
volumes:
    postgres:
