version: "3.9"
services:
  backend:
    build:
      context: applications/backend/

    restart: always

    depends_on:
      - database

  frontend:
    build:
      context: applications/frontend/

    ports:
      - "80:3000"

    restart: always

    depends_on:
      - backend

  database:
    image: postgres:latest

    environment:
      POSTGRES_DB: findit
      POSTGRES_USER: webserver
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata

    restart: always

    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
volumes:
    postgres:
