version: '3.9'
name: findit-development
services:
  store:
    extends:
      file: docker-compose.yml
      service: store
    build:
      args:
        - ENV=development
    volumes:
      - ./applications/store/data/development:/data:rw

  database:
    extends:
      file: docker-compose.yml
      service: database
    environment:
      - POSTGRES_DB=development
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "webserver", "-d", "development" ]
    volumes:
      - ./applications/database/data/development:/var/lib/postgresql/data/pg-data:rw

  backend:
    extends:
      file: docker-compose.yml
      service: backend
    build:
      target: backend-development
      args:
        - ENV=development
    depends_on:
      database:
        condition: service_healthy
      store:
        condition: service_healthy
    env_file:
      - ./applications/backend/.env.development

    #    volumes:
    #      - ./applications/backend/:/project/apps/backend/

    ports:
      - '3001:3001'
      - '5555:5555'

  frontend:
    extends:
      file: docker-compose.yml
      service: frontend
    build:
      target: frontend-development
      args:
        - ENV=development
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./applications/frontend/.env.development

    ports:
      - '3000:3000'