version: "3.9"
services:
  backend:
    container_name: backend
    build:
      context: applications/backend/
      dockerfile: Dockerfile

    restart: always

    depends_on:
      - database

  frontend:
    container_name: frontend
    build:
      context: applications/frontend/
      dockerfile: Dockerfile

    ports:
      - "0.0.0.0:80:3000"

    restart: always

    depends_on:
      - backend

  database:
    container_name: database
    image: postgres:latest

    environment:
      POSTGRES_DB: findit
      POSTGRES_USER: webserver
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pg-data

    restart: always

    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
volumes:
    postgres:
