name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v5
      
    - name: Run test on the Docker image
      run: make test

  development:
    runs-on: ubuntu-latest
    environment:
      name: development
      
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v5
      
    - name: Run development env inside Docker
      run: make start-dev
