name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run test on the Docker image
      run: make test

  development:
    runs-on: ubuntu-latest
    environment:
      name: development
      
    steps:
    - uses: actions/checkout@v3
    - name: Run development env inside Docker
      run: make start-dev
