name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run test
      run: make test

  # development:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
      
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
      
  #   - name: Run development
  #     run: make start-dev
