name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4
      
    - name: Run
      run: make test-backend

  frontend-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - name: Run
      run: make test-frontend

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs:
      - backend-tests
      - frontend-tests

    steps:
    - uses: actions/checkout@v4

    - name: Install deps
      run: npm i -ws && npm i -D -ws

    - name: Run
      run: npm run lint -ws

    - name: Remove deps
      run: npm prune -ws

  # development:
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: development
      
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v4
      
  #   - name: Run development
  #     run: make start-dev
